name: Java CI with Maven
on:
  push:
    branches: [ 2.1.x ]
  pull_request:
    branches: [ 2.1.x ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install
      run: ./mvnw install -DskipTests
    - name: Unit tests
      run: ./mvnw surefire:test
    - name: Integration tests
      run: ./mvnw failsafe:integration-test
